sudo: required

services:
  - docker

language: java

jobs:
  include:
    - # require the branch name to be master (note for PRs this is the base branch name)
      if: branch = producao
      env: VAR=" "AMBIENTE=PRODUCAO" "


branches:
  only:
    - producao
    - homologacao
    - desenvolvimento

before_install:
  - docker build -t teste/hello  .
  - docker info

script: docker run -it --rm=true -e $VAR teste/hello
