branches:
  only:
  - master

  sudo: required

  language: java

  services:
    - docker

  before_install:
    - docker build -t teste/hello  . 

  script:
   - docker run -it --rm=true teste/hello -e AMBIENTE=PRODUCAO



  
