sudo: required

services:
  - docker

language: java


branches:
  only:
    - produção
    - homologacao
    - desenvolvimento

before_install:
  - docker build -t teste/hello  .
  - docker info

script: docker run -it --rm=true teste/hello
