sudo: required

services:
  - docker

language: java

branches:
  only:
    - producao
    - homologacao
    - desenvolvimento

before_install:
  - docker build -t teste/hello  .

script:
  - if [ "$TRAVIS_BRANCH" = "producao" ]; then docker run -it --rm=true -e "AMBIENTE=PRODUCAO"  teste/hello; fi
  - if [ "$TRAVIS_BRANCH" = "homologacao" ]; then docker run -it --rm=true -e "AMBIENTE=HOMOLOGACAO" teste/hello; fi
